print("----------------------------------------")
print("Succeded, amount deposited to",                                                            "|")
print("                                                     |")
print("                                                     |")
print("----------------------------------------")
